# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "master" do |master|
    master.vm.network "private_network", ip: "192.168.191.10"
    master.vm.hostname = "salt"
    master.vm.box = "debian/stretch64"
  end

  config.vm.define "minion1" do |minion1|
    minion1.vm.network "private_network", ip: "192.168.191.11"
    minion1.vm.hostname = "minion1"
    minion1.vm.box = "debian/stretch64"

    # add salt private network IP to hosts file
    minion1.vm.provision "shell", inline: <<-SHELL
      echo 192.168.191.10 salt >> /etc/hosts
    SHELL
  end

  config.vm.define "minion2" do |minion2|
    minion2.vm.network "private_network", ip: "192.168.191.12"
    minion2.vm.hostname = "minion2"
    minion2.vm.box = "debian/stretch64"

    # add salt private network IP to hosts file
    minion2.vm.provision "shell", inline: <<-SHELL
      echo 192.168.191.10 salt >> /etc/hosts
    SHELL
  end

end